name: ocnera
description: Ombi Content Request Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ## Http client
  dio: ^3.0.9
  ## permission handler
  permission_handler: ^5.0.0+hotfix.5
  ## JSON configuration handler
  global_configuration: ^1.5.0
  ## Spinners animation
  flutter_spinkit: ^4.1.2+1
  ## Stream handler
  rxdart: ^0.24.0
  ## Secure storage
  flutter_secure_storage: ^3.3.3
  ## Download & Cache network images.
  cached_network_image: ^2.2.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  ## For DateTime formatting
  intl: ^0.16.1
  ## For background animation
  simple_animations: ^2.2.1
  ## For refresh view
  pull_to_refresh: ^1.6.1
  ## Logger
  logger: ^0.9.2
  ##Fimber for logging
  fimber_io: '0.4.3'
  flutter_fimber: '0.4.3'
  ##path_provider for logging and storage
  path_provider: ^1.6.21
  ## For customizing list items
  list_tile_more_customizable: '1.2.2'
  ## For local settings
  shared_preferences: ^0.5.7
  enum_to_string: ^1.0.13
  ## For localizing the app
  easy_localization: '2.3.3'
  cider: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  ## TODO - Check if you really need this one.
  flutter_staggered_grid_view: ^0.3.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/translations/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
